---
function:
  name: omni-cw-invoices-to-coupa-${self:provider.stage}
  handler: src/cw-invoices-to-coupa/index.handler
  runtime: nodejs20.x
  timeout: 900
  layers:
    - { Ref: NodeModulesLambdaLayer }
  package:
    include:
      - 'src/cw-invoices-to-coupa/**'
      - 'src/shared/**'
    exclude:
      - '**/*'
  # events:
  #   - schedule: cron(*/30 * * * ? *)
  environment:
    # DB_NAME: ${ssm:/omni-dw/${self:provider.stage}/rds/db.name}
    # DB_USERNAME: ${ssm:/omni-dw/${self:provider.stage}/rds/db.username}
    # DB_HOST: ${ssm:/omni-dw/${self:provider.stage}/rds/db.endpoint.ip}
    # DB_PORT: ${ssm:/omni-dw/${self:provider.stage}/rds/db.port}
    # DB_PASSWORD: ${ssm:/omni-dw/${self:provider.stage}/rds/db.password}